config/routes.rb
Retro::Application.routes.draw do
  
  devise_for :users
  root 'home#about'

  resources :sretros do 
	 resources :notes
     patch '/retro_notes/close', to: "notes#close"

     get 'action_items'
     post 'action_items', to: "action_items#create"
     post 'action_items/update'
     get 'action_items/new'
     get 'action_items/edit'
  end

  post "search", to: "search#notes", as: :search

  namespace :api do
    namespace :v1 do
      resources :users, only: [:create, :update, :delete, :show]
      post 'users/login', to: 'users#login', as: :login
      resources :teams, only: [:index]

      resources :sretros do
        resources :notes, only: [:create, :show, :index]
      end
    end
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  #belongs_to :sretro
  belongs_to :note_type

  searchkick word_start: [:notes]
end

app/models/note_type.rb
class NoteType < ActiveRecord::Base
	#has_one :note
end

app/controllers/api/v1/notes_controller.rb
class Api::V1::NotesController < ApplicationController
      protect_from_forgery
      skip_before_action :verify_authenticity_token
      
	def create
		@user = User.find(notes_params[:user_id])
		@note = @user.notes.build(notes_params)
		@note.sretro_id = params[:sretro_id]
		if @note.save
			render status: 200, json: {
				message: "Success",
				content: @note
			}
		else
			render status: 400, json: {
				message: "Error"
			}
		end
	end

	def index

		notes = Notes.new
		begin
			notes_hash = notes.get_list_of_notes notes_params
			get_action_items
			render status: 200, json: {
				message: "Success",
				content: notes_hash["notes"]
			}
		rescue Exception => e
			render status: 400, json: {
				message: e.message
			}
		end
	end

	private

	def notes_params
		params.permit(:user_id, :notes, :note_type_id, :sretro_id)
	end

	def get_action_items
		@action_items = ActionItem.where(sretro_id: params[:sretro_id])
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_filter :get_retro_by_id

	def new
		@note = Note.new
	end

	def index
		
		@retros= current_user.team.sretros.where(id: params[:sretro_id]).to_ary
		@notes = @retros.map { |e| e.notes }
		@notes.flatten! #I am sure there is a better way to handle this
		@notes_names  = @notes.map { |e|  e.note_type.name }
		@notes_names.uniq!
		get_action_items
	end

	def create
		@note = current_user.notes.build(notes_params)
		@note.sretro_id = params[:sretro_id]
		
		if @note.save
			redirect_to sretro_note_path(@sretro, @note)
			flash[:notice] = "Your notes has been created successfull."
		else
			flash[:alert] = "Error creating a note. Try agian later"
		end
	end

	def edit
		@note = Note.find(params[:id])
	end

	def update
		@note = Note.find(params[:id])
		if @note.update(notes_params)
			redirect_to sretro_note_path(@sretro, @note)
			flash[:notice] = "Note has been updated successfully."
		else
			flash[:alert] = "Error creating a note. Try agian later"
		end
	end

	def destroy
    	@note = Note.find(params[:id])
    	@note.destroy
 
    	redirect_to sretro_notes_path(@sretro)
 	end
 	
 	def close
 		@sretro.is_pending = 0
 		@sretro.save
 		respond_to do |format|
			format.js {render nothing: true} 
		end
 	end

	def show
		@note = Note.find(params[:id])
	end

	private

	def notes_params
		params.require(:note).permit(:sretro_id, :notes, :note_type_id)
	end

	def get_retro_by_id
		@sretro = Sretro.find(params[:sretro_id])
	end

	def get_action_items
		@action_items = ActionItem.where(sretro_id: params[:sretro_id])
	end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/edit.html.erb
<div class="container">

	<%= form_for [@sretro, @note] do |f| %>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>Edit Note</h1>
				<p><%= link_to "Summary", sretro_notes_path(@sretro) %></p>
			</div>
			<div class="panel-body">
				<%= f.text_area :notes, size: "100x10" %><br>
		        <%= f.select(:note_type_id, NoteType.all.map{ |c| [c.name, c.id] }, :include_blank => "--Note Type--") %>
			</div>
			<div class="panel-footer">
				<%= f.submit "Save", class: 'btn btn-primary btn-lg', data: {disable_with: "Saving.."} %>
			</div>
		</div>
		<div>
			<%= link_to "Previous Retros", sretros_path %>
		</div>
	<% end %>

</div>

app/views/notes/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">			
			<div class="panel panel-default">
				<div class="panel-heading">
					<h1><%= @sretro.title %> - Summary</h1>
					<%= button_tag "Submit my votes", id: "submit_votes", data: {disable_with: "Saving..", sretro_id: @sretro.id}, class: "btn btn-default btn-primary" %>
					<p>You only get 3 votes.</p>
				</div>
				<div class="panel-body">
					<% @notes.each do |note| %>
						<div class="panel panel-default">
							<div class="panel-heading">
								<h3><%= note.note_type.name %></h3>
							</div>
							<div class="panel-body">
								<p>
									<%= check_box_tag :vote, '', false, class: "note_vote_class" %>
									<%= note.notes %>
								</p>	
							</div>
							<div class="panel-footer">
								<% if current_user == note.user %>
									<%= link_to "Edit", edit_sretro_note_path(@sretro, note) %> |
									<%= link_to "Delete", sretro_note_path(@sretro, note), method: :delete, data: { confirm: 'Are you sure?' } %>
								<% end %>
							</div>
						</div>
					<% end %>
				</div>
				<% if current_user.is_team_lead? && @sretro.is_pending? %>
					<div class='panel-footer'>
							<%= button_tag "Save and close retro", id: "finish_retro", data: {disable_with: "Saving..", sretro_id: @sretro.id}, class: "btn btn-lg btn-primary" %>
							<%= link_to "New Note", new_sretro_note_path(@sretro), class: "pull-right" %>
					</div>
				<% end %>
			</div>	
		</div>
		<div class="col-md-6">
			<%= form_for [@sretro, @sretro.action_items.build] do |f| %>
				<div class="well well-lg">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h1>Action Items</h1>
						</div>
						<div class="panel-body">
							<%= f.text_area :description, cols: 50, rows: 10 %>
						</div>
						<div class="panel-footer">
							<%= f.submit "Save", class: "btn btn-lg btn-primary", data: {disable_with: "Saving..."} %>
						</div>
					</div>
				</div>
				<div class="well">
					<h4>Vote on action items. You will have 3 votes</h4>
					<% @action_items.each do |item| %>
						<ul>
							<li>
								<%= item.description %>
							</li>
						</ul>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/notes/new.html.erb
<div class="container">

	<%= form_for [@sretro, @note]  do |f| %>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>New Note</h1>
				<p><%= link_to "Summary", sretro_notes_path(@sretro) %></p>
			</div>
			<div class="panel-body">
				<%= f.text_area :notes, size: "100x10" %><br>
		        <%= f.select(:note_type_id, NoteType.all.map{ |c| [c.name, c.id] }, :include_blank => "--Note Type--") %>
			</div>
			<div class="panel-footer">
				<%= f.submit "Save", class: 'btn btn-primary btn-lg', data: {disable_with: "Saving.."} %>
			</div>
		</div>
		<div>
			<%= link_to "Previous Retros", sretros_path %>
		</div>
	<% end %>

</div>

app/views/notes/show.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h1>Show Notes</h1>
			<%= link_to "Summary", sretro_notes_path(@sretro)%>
		</div>
		<div class="panel-body">
			<h1><%= @note.note_type.name %></h1>
			<p>
				<%= @note.notes %>
			</p>
		</div>

		<div class="panel-footer">
			<%= link_to "New Note", new_sretro_note_path(@sretro) %>
		</div>
	</div>
</div>