config/routes.rb
Retro::Application.routes.draw do
  
  devise_for :users
  root 'home#about'

  resources :sretros do 
	 resources :notes
     patch '/retro_notes/close', to: "notes#close"

     get 'action_items'
     post 'action_items', to: "action_items#create"
     post 'action_items/update'
     get 'action_items/new'
     get 'action_items/edit'
  end

  post "search", to: "search#notes", as: :search

  namespace :api do
    namespace :v1 do
      resources :users, only: [:create, :update, :delete, :show]
      post 'users/login', to: 'users#login', as: :login
      resources :teams, only: [:index]

      resources :sretros do
        resources :notes, only: [:create, :show, :index]
      end
    end
  end
end

app/models/sretro.rb
class Sretro < ActiveRecord::Base
	#belongs_to :user
	belongs_to :team
	has_many :notes
	has_many :action_items
end

app/controllers/api/v1/sretros_controller.rb
class Api::V1::SretrosController < ApplicationController
	  protect_from_forgery
      skip_before_action :verify_authenticity_token
	
	def index
		@user = User.find(user_params[:user_id])
		@sretros = @user.team.sretros
		
		if @sretros
			render status: 200, json: {
				message: "Success",
				content: @sretros
			}
		else
			render status: 400, json: {
				message: "Error"
			}
		end
	end

  def create
	@user = User.find(user_params[:user_id])
    @sretro = Sretro.new(user_params)

    if @sretro.save
			render status: 200, json: {
				message: "Success",
				content: @sretro
			}
		else
			render status: 400, json: {
        message: @sretro.errors.full_messages.join(", "),
			}
		end
  end

 	private

    def user_params
      params.permit(:user_id,:title, :style, :team_id)
    end

    def sretro_params
      params.permit(:title, :style, :team_id)
    end
end

app/controllers/sretros_controller.rb
class SretrosController < ApplicationController
	before_action :authenticate_user!
	
	def new
		@sretro = Sretro.new
	end

	def show
		
	end

	def index
		@sretros = current_user.team.sretros
	end

	def create
		@user_team = current_user.team
		@sretro = Sretro.new(sretro_params)

		respond_to do |format|
			if @sretro.save
				format.html { redirect_to new_sretro_note_path(sretro_id: @sretro.id), notice: "Retro has been created"} 
			else
				format.html { render action: 'new'}
			end
		end
	end

	private

	def sretro_params
		params.require(:sretro).permit(:title, :style, :team_id)
	end
end

app/views/sretros/index.html.erb
<div class="container">

	<div class="panel panel-default">
			<div class="panel-heading">
				<h1>Retro List</h1>
			</div>
			<div class="panel-body">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Retro Title</th>
							<th>Created</th>
						</tr>
					</thead>
					<% @sretros.each do |retro| %>
						<tbody>
							<tr>
								<th scope="row"><%= link_to retro.title, sretro_notes_path(retro) %></th>
								<% if retro.is_pending? %>
									<td><p><%= link_to "New Note", new_sretro_note_path(retro) %></p></td>
								<% end %>
								<td><%= time_ago_in_words(retro.created_at) %> ago</td>
							</tr>
						</tbody>
					<% end %>
				</table>
			</div>
			<% if current_user.is_team_lead? %>
				<div class="panel-footer">
					<%= link_to "Create new retro", new_sretro_path %>
				</div>
			<% end %>
	</div>
</div>

app/views/sretros/new.html.erb
<div class="container">
	
	<%= form_for @sretro, url: :sretros do |f| %>
		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="panel-title">
					<h1>Create new Retro</h1>
				</div>
			</div>
			<div class="panel-body ">
				<div class="form-group">
					<%= f.text_field :title, class: "form-control"%>	
				</div>
				<div class="form-group">
					<%= f.select(:style, options_for_select([ ['Select retro style', ""], ['Basic', "Basic"], ['Star Fish', "Star Fish"] ]), class: 'form-control' ) %>
				</div>	
			</div>
			<div class="panel-footer">
				<%= f.submit "Create", class: 'btn btn-lg btn-primary' %>
			</div>
		</div>
	<% end %>
</div>